In [1]:
import itertools
from abc import ABC, abstractmethod
from typing import Literal

import mlflow
import numpy as np
import pandas as pd
from numpy.typing import NDArray
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.model_selection import KFold, train_test_split
from sklearn.pipeline import Pipeline

from utils import data_cleaning, get_preprocessor

In [2]:
# np.number is a base class for all integers, floating numbers in numpy
# In Python 3.12, type keyword wass introduced to replace typing.TypeAlias
# read more about this https://docs.astral.sh/ruff/rules/non-pep695-type-alias/
type Vector = NDArray[np.integer | np.floating]
type Matrix = NDArray[np.integer | np.floating]
type Scalar = int | float | np.integer | np.floating

# These are old alternatives
# Vector: TypeAlias = NDArray[np.integer | np.floating]
# Matric: TypeAlias = NDArray[np.integer | np.floating]
# Scalar: TypeAlias = int | float | np.integer | np.floating

In [3]:
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("Car Price Prediction")

<Experiment: artifact_location='mlflow-artifacts:/769694705593400528', creation_time=1757233222067, experiment_id='769694705593400528', last_update_time=1757233222067, lifecycle_stage='active', name='Car Price Prediction', tags={}>

## Lasso Penalty
$$
\text{L1} = \lambda\sum_{j=1}^{n}|\theta_{j}|

## Ridge Penalty
$$
\text{L2} = \lambda\sum_{j=1}^{n}\theta_{j}^2

In [7]:
class BasePenalty(ABC):
    @abstractmethod
    def __call__(self, theta: Vector) -> Scalar:
        pass

    @abstractmethod
    def derivation(self, theta: Vector) -> Vector:
        pass


class LassoPenalty(BasePenalty):
    def __init__(self, l: Scalar) -> None:
        self.l = l  # lambda value

    # __call__ allows call class as method
    def __call__(self, theta: Vector) -> Scalar:
        return self.l * np.sum(np.abs(theta[1:]))  # do not regularize bias term

    def derivation(self, theta: Vector) -> Vector:
        g = np.zeros_like(theta)
        g[1:] = self.l * np.sign(theta[1:])  # do not regularize bias term
        return g


class RidgePenalty(BasePenalty):
    def __init__(self, l: Scalar) -> None:
        self.l = l

    def __call__(self, theta: Vector) -> Scalar:
        return self.l * np.sum(np.square(theta[1:]))  # do not regularize bias term

    def derivation(self, theta: Vector) -> Vector:
        g = np.zeros_like(theta)
        g[1:] = self.l * 2 * (theta[1:])  # do not regularize bias term
        return g


# class ElasticPenalty(BasePenalty):
#     def __init__(self, l: Scalar = 0.1, l_ratio: Scalar = 0.5) -> None:
#         self.l = l
#         self.l_ratio = l_ratio

#     def __call__(self, theta: Vector) -> Scalar:
#         # The coefficient 1 is to avoid double counting of lambda
#         # Also, do not regularize the bias term but this is handled in Lasso and Ridge
#         # So just pass the full theta
#         l1_contribution = self.l_ratio * LassoPenalty(1)(theta)
#         l2_contribution = (1 - self.l_ratio) * RidgePenalty(1)(theta)
#         return self.l * (l1_contribution + l2_contribution)

#     def derivation(self, theta: Vector) -> Vector:
#         # The coefficient 1 and passing full theta is here as well
#         l1_derivation = self.l_ratio * LassoPenalty(1).derivation(theta)
#         l2_derivation = (1 - self.l_ratio) * RidgePenalty(1).derivation(theta)
#         return self.l * (l1_derivation + l2_derivation)

In [8]:
from dataclasses import dataclass

type TrainMethod = Literal["batch", "stochastic", "mini-batch"]
type WeightInitMethod = Literal["zero", "xavier"]


@dataclass
class KFoldScore:
    train_loss: float
    val_loss: float
    val_r2: float

In [ ]:
class LinearRegression(BaseEstimator, RegressorMixin):
    cv = KFold(n_splits=3, shuffle=True, random_state=42)

    def __init__(
        self,
        regularization: BasePenalty | None,
        momentum: float,
        train_method: TrainMethod,
        weight_init_method: WeightInitMethod,
        lr: Scalar,
        num_epochs: int,
        batch_size: int | None,
        params_for_logging: dict,
    ) -> None:
        if (train_method in {"batch", "stochastic"}) and batch_size is not None:
            print("Error: Batch size should be None for batch or stochastic gradient descent.")
            return
        if train_method == "mini-batch" and (batch_size is None or batch_size <= 0):
            print("Error: Please provide a valid batch size for mini-batch gradient descent.")
            return
        if regularization is not None and not issubclass(type(regularization), BasePenalty):
            print("Error: regularization should be a subclass of BasePenalty or None.")
            return

        self.regularization = regularization
        self.momentum = momentum
        self.train_method = train_method
        self.weight_init_method = weight_init_method
        self.lr = lr
        self.num_epochs = num_epochs
        self.batch_size = batch_size
        self.params_for_logging = params_for_logging

    def mse(self, ytrue: Vector, ypred: Vector) -> Scalar:
        return ((ypred - ytrue) ** 2).sum() / ytrue.shape[0]

    def r_squared(self, ytrue: Vector, ypred: Vector) -> Scalar:
        # Formula is 1 - SSres / SStot
        # SSres = Sum of squared residual
        # SStot = Sum of squared totsl (compared to the mean or ybar)
        return 1 - np.sum(np.square(ytrue - ypred)) / np.sum(np.square(ytrue - ytrue.mean()))

    def xavier_weight_init(self, m: int, n: int) -> Vector:
        # Since this method use number of samples to calculate a new uniform range,
        # it requires both m and n to initialize theta (n, )
        upper = 1 / np.sqrt(m)
        lower = -(upper)
        numbers = np.random.rand(n)
        # The scaled output is calculated by
        # 1. streching U(0, 1) into U(0, upper - lower)
        #    with upper - lower = length between lower and upper
        # 2. Add lower to shift all the numbers back to U(lower, upper)
        return lower + numbers * (upper - lower)

    def zero_weight_init(self, n: int) -> Vector:
        return np.zeros(n)

    def weight_init(self, X: Matrix) -> Vector:
        if self.weight_init_method == "zero":
            self.theta = np.zeros(X.shape[1])
        elif self.weight_init_method == "xavier":
            self.theta = self.xavier_weight_init(X.shape[0], X.shape[1])

    def add_intercept(self, X: Matrix) -> Matrix:
        return np.hstack([np.ones((X.shape[0], 1)), X])

    def fit(self, X_train: Matrix, y_train: Vector) -> None:
        # create a list of kfold scores
        self.kfold_scores: list[KFoldScore] = []

        # kfold.split in the sklearn.....
        for fold, (train_idx, val_idx) in enumerate(self.cv.split(X_train)):
            # reset val loss at the start of each fold, not outside the fold loop
            self.val_loss_old = np.inf
            self.val_r2_old = -np.inf

            X_cross_train = X_train[train_idx]
            y_cross_train = y_train[train_idx]
            X_cross_val = X_train[val_idx]
            y_cross_val = y_train[val_idx]

            # add intercept column to training set as well as validation set
            # so that theta[0] is the bias / intercept
            # X_cross_train has size (m, n+1)
            # X_cross_val has size (m, n+1)
            X_cross_train = self.add_intercept(X_cross_train)
            X_cross_val = self.add_intercept(X_cross_val)

            # define X_cross_train as only a subset of the data
            # how big is this subset?  => mini-batch size ==> 50

            # initialize theta for each fold
            self.weight_init(X_cross_train)
            # This should be vector of same shape as theta
            # but initialized to zero as it will broadcasted anyway
            self.prev_step = 0  # for momentum

            # one epoch will exhaust the WHOLE training set
            with mlflow.start_run(run_name=f"Fold-{fold}", nested=True):
                mlflow.log_params(self.params_for_logging)

                for epoch in range(self.num_epochs):
                    # with replacement or no replacement
                    # with replacement means just randomize
                    # with no replacement means 0:50, 51:100, 101:150, ......300:323
                    # shuffle your index
                    # https://docs.astral.sh/ruff/rules/numpy-legacy-random/
                    perm = np.random.permutation(X_cross_train.shape[0])

                    X_cross_train = X_cross_train[perm]
                    y_cross_train = y_cross_train[perm]

                    train_loss = self.start_training(X_cross_train, y_cross_train)

                    yhat_val = self.predict(X_cross_val, add_intercept=False)
                    val_loss_new = self.mse(y_cross_val, yhat_val)
                    val_r2_new = self.r_squared(y_cross_val, yhat_val)
                    mlflow.log_metrics(
                        {
                            "train_loss": train_loss,
                            "val_loss": val_loss_new,
                            "val_r2": val_r2_new,
                        },
                        step=epoch,
                    )

                    # early stopping
                    if np.allclose(val_loss_new, self.val_loss_old):
                        break
                    self.val_loss_old = val_loss_new
                    self.val_r2_old = val_r2_new

                self.kfold_scores.append(
                    KFoldScore(
                        train_loss=train_loss,
                        val_loss=val_loss_new,
                        val_r2=val_r2_new,
                    ),
                )
                print(f"Fold {fold} Train Loss: {train_loss}")
                print(f"Fold {fold} Val Loss:   {val_loss_new}")
                print(f"Fold {fold} Val R2:     {val_r2_new}")

    def start_training(self, X_train: Matrix, y_train: Vector) -> float:
        if self.train_method == "stochastic":
            for batch_idx in range(X_train.shape[0]):
                # (11,) ==> (1, 11) ==> (m, n)
                X_method_train = X_train[batch_idx].reshape(1, -1)
                y_method_train = y_train[batch_idx].reshape(1)  # So this has shape (1,) -> not scalar
                train_loss = self._train(X_method_train, y_method_train)
        elif self.train_method == "mini-batch":
            for batch_idx in range(0, X_train.shape[0], self.batch_size):
                # batch_idx = 0, 50, 100, 150
                X_method_train = X_train[batch_idx : batch_idx + self.batch_size, :]
                y_method_train = y_train[batch_idx : batch_idx + self.batch_size]
                train_loss = self._train(X_method_train, y_method_train)
        elif self.train_method == "batch":
            X_method_train = X_train
            y_method_train = y_train
            train_loss = self._train(X_method_train, y_method_train)
        else:
            msg = "Error: Please select correct training method."
            raise ValueError(msg)
        return train_loss

    def _train(self, X: Matrix, y: Vector) -> Scalar:
        yhat = self.predict(X, add_intercept=False)
        m = X.shape[0]
        grad_loss = (2 / m) * X.T @ (yhat - y)
        if self.regularization is not None:  # noqa: SIM108
            grad_penalty = self.regularization.derivation(self.theta) / m
        else:
            grad_penalty = 0
        grad = grad_loss + grad_penalty
        step = self.lr * grad
        # If momentum is 0, second term is 0, so no momentum
        self.theta = self.theta - step + self.momentum * self.prev_step
        self.prev_step = step

        return self.mse(y, yhat)

    def predict(self, X: Matrix, *, add_intercept: bool = True) -> Vector:
        if add_intercept:
            X = self.add_intercept(X)
        return X @ self.theta  # ===>(m, n) @ (n, )

    def _coef(self) -> Vector:
        return self.theta[1:]  # remind that theta is (w0, w1, w2, w3, w4.....wn)
        # w0 is the bias or the intercept
        # w1....wn are the weights / coefficients / theta

    def _bias(self) -> Scalar:
        return self.theta[0]

    def get_average_kfold_scores(self) -> KFoldScore:
        # return the average of the kfold scores
        return KFoldScore(**pd.DataFrame(self.kfold_scores).mean().to_dict())

    def plot_feature_importance(self, feature_names: list[str]) -> None:
        import matplotlib.pyplot as plt

        coef = self._coef()
        if len(coef) != len(feature_names):
            print("Error: Length of feature names must match number of features.")
            return

        feature_importance = pd.Series(coef, index=feature_names).sort_values(ascending=False)

        plt.figure(figsize=(10, 6))
        feature_importance.plot(kind="barh")
        plt.title("Feature Importance")
        plt.ylabel("Coefficient Value")
        plt.xlabel("Feature")
        plt.tight_layout()
        plt.show()


class Lasso(LinearRegression):
    def __init__(
        self,
        l: Scalar,
        momentum: float,
        train_method: TrainMethod,
        weight_init_method: WeightInitMethod,
        lr: Scalar,
        num_epochs: int,
        batch_size: int | None,
        params_for_logging: dict,
    ) -> None:
        super().__init__(
            regularization=LassoPenalty(l),
            momentum=momentum,
            train_method=train_method,
            weight_init_method=weight_init_method,
            lr=lr,
            num_epochs=num_epochs,
            batch_size=batch_size,
            params_for_logging=params_for_logging,
        )


class Ridge(LinearRegression):
    def __init__(
        self,
        l: Scalar,
        momentum: float,
        train_method: TrainMethod,
        weight_init_method: WeightInitMethod,
        lr: Scalar,
        num_epochs: int,
        batch_size: int | None,
        params_for_logging: dict,
    ) -> None:
        super().__init__(
            regularization=RidgePenalty(l),
            momentum=momentum,
            train_method=train_method,
            weight_init_method=weight_init_method,
            lr=lr,
            num_epochs=num_epochs,
            batch_size=batch_size,
            params_for_logging=params_for_logging,
        )


# class ElasticNet(LinearRegression):
#     def __init__(
#         self,
#         l: Scalar,
#         l_ratio: Scalar,
#         momentum: float,
#         train_method: TrainMethod,
#         weight_init_method: WeightInitMethod,
#         lr: Scalar,
#         num_epochs: int,
#         batch_size: int | None,
#         params_for_logging: dict,
#     ) -> None:
#         super().__init__(
#             regularization=ElasticPenalty(l, l_ratio),
#             momentum=momentum,
#             train_method=train_method,
#             weight_init_method=weight_init_method,
#             lr=lr,
#             num_epochs=num_epochs,
#             batch_size=batch_size,
#             params_for_logging=params_for_logging,
#         )

In [10]:
# Load, Clean, Split, Preprocess Data
df = pd.read_csv("Cars.csv")
df_train, df_test = train_test_split(df, random_state=42, test_size=0.2)
df_train = data_cleaning(df_train)
df_test = data_cleaning(df_test)
X_train = df_train.drop(columns=["selling_price"])
X_test = df_test.drop(columns=["selling_price"])
y_train = df_train["selling_price"]
y_test = df_test["selling_price"]

In [11]:
X_train.shape

(6421, 11)

In [12]:
print("X_train shape:", X_train.shape, type(X_train))
print("X_test shape:", X_test.shape, type(X_test))
print("y_train shape:", y_train.shape, type(y_train))
print("y_test shape:", y_test.shape, type(y_test))

X_train shape: (6421, 11) <class 'pandas.core.frame.DataFrame'>
X_test shape: (1607, 11) <class 'pandas.core.frame.DataFrame'>
y_train shape: (6421,) <class 'pandas.core.series.Series'>
y_test shape: (1607,) <class 'pandas.core.series.Series'>

In [13]:
model_types = ["Normal", "Ridge", "Lasso", "Polynomial"]
momentum = [0, 0.9]  # 0 means no momentum
train_methods = ["batch", "stochastic", "mini-batch"]
weight_init_methods = ["zero", "xavier"]
learning_rates = [0.01, 0.001, 0.0001]


all_combinations = list(
    itertools.product(
        model_types,
        momentum,
        train_methods,
        weight_init_methods,
        learning_rates,
    ),
)
keys = ["model_type", "momentum", "train_method", "weight_init_method", "learning_rate"]
params_combinations = [dict(zip(keys, comb, strict=False)) for comb in all_combinations]
len(params_combinations)

144

In [14]:
def start_experiment(
    X_train_original: pd.DataFrame,
    y_train_original: pd.Series,
    params_combinations: list[dict],
    num_epochs: int = 500,
    batch_size: int = 32,
) -> None:
    from utils import Lasso, LinearRegression, Ridge

    for params in params_combinations:
        # Populate all params with num_epochs, batch_size, and lambda (if applicable)
        params["num_epochs"] = num_epochs
        if params["train_method"] == "mini-batch":
            params["batch_size"] = batch_size
            train_method_log_string = f"{params['train_method']}_BatchSize-{params['batch_size']}"
        else:
            params["batch_size"] = None
            train_method_log_string = f"{params['train_method']}"
        if params["model_type"] in {"Ridge", "Lasso"}:
            params["lambda"] = 0.1

        log_string = (
            f"Reg-{params['model_type']}"
            f"_TrainMethod-{train_method_log_string}"
            f"_Momentum-{params['momentum']}"
            f"_WeightInit-{params['weight_init_method']}"
            f"_LR-{params['learning_rate']}"
        )
        mlflow.start_run(run_name=log_string)
        mlflow.log_params(params)

        print("=" * 40)
        print(log_string)

        if params["model_type"] in ["Normal", "Polynomial"]:
            model = LinearRegression(
                regularization=None,
                momentum=params["momentum"],
                train_method=params["train_method"],
                weight_init_method=params["weight_init_method"],
                lr=params["learning_rate"],
                num_epochs=params["num_epochs"],
                batch_size=params["batch_size"],
                params_for_logging=params,
            )
        elif params["model_type"] == "Ridge":
            model = Ridge(
                l=params["lambda"],
                momentum=params["momentum"],
                train_method=params["train_method"],
                weight_init_method=params["weight_init_method"],
                lr=params["learning_rate"],
                num_epochs=params["num_epochs"],
                batch_size=params["batch_size"],
                params_for_logging=params,
            )
        elif params["model_type"] == "Lasso":
            model = Lasso(
                l=params["lambda"],
                momentum=params["momentum"],
                train_method=params["train_method"],
                weight_init_method=params["weight_init_method"],
                lr=params["learning_rate"],
                num_epochs=params["num_epochs"],
                batch_size=params["batch_size"],
                params_for_logging=params,
            )
        else:
            print("Error: Please select correct model type.")
            break

        if params["model_type"] == "Polynomial":
            pipeline = Pipeline(steps=[("preprocess", get_preprocessor(polynomial_degree=2))])
        else:
            pipeline = Pipeline(steps=[("preprocess", get_preprocessor())])
        pipeline.steps.append(("model", model))
        pipeline.fit(X_train_original, y_train_original)

        # Get model from pipeline
        # (last step so index = -1)
        # and it's a tuple of (name, model) so get the model with [1]
        fitted_model: LinearRegression = pipeline.steps[-1][1]
        avg_kfold_scores: KFoldScore = fitted_model.get_average_kfold_scores()

        print("Average training loss (MSE): ", avg_kfold_scores.train_loss)
        print("Average validation loss (MSE): ", avg_kfold_scores.val_loss)
        print("Average validation R2: ", avg_kfold_scores.val_r2)

        mlflow.log_metric(key="avg_train_mse", value=avg_kfold_scores.train_loss)
        mlflow.log_metric(key="avg_val_mse", value=avg_kfold_scores.val_loss)
        mlflow.log_metric(key="avg_val_r2", value=avg_kfold_scores.val_r2)

        # No logging the model for now as i need to fit model again
        # based on the the best average val loss
        # signature = mlflow.models.infer_signature(X_train_original, pipeline.predict(X_train_original))
        # mlflow.sklearn.log_model(pipeline, name="skpipeline", signature=signature)

        mlflow.end_run()

In [12]:
params_combinations[107]

{'model_type': 'Lasso',
 'momentum': 0.9,
 'train_method': 'mini-batch',
 'weight_init_method': 'xavier',
 'learning_rate': 0.0001}

In [ ]:
mlflow.end_run()  # just in case there is some run stuck

In [24]:
# suppress overflow warnings for log
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore", RuntimeWarning)
    start_experiment(
        X_train,
        np.log(y_train.to_numpy()),
        params_combinations=params_combinations,
        num_epochs=500,
        batch_size=50,  # only used for mini-batch training, will be ignored otherwise
    )

========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.01
Fold 0: inf
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/d0eebc8bb763444d869a67b04b6fd3e7
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: inf
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/4dc614dc412d4d26a59111ce4cb990f5
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: inf
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/eca6c189ab01447aa5306beaabdcda16
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  inf
Average validation loss (MSE):  inf
Average validation R2:  -inf
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.01 at: http://localhost:5000/#/experiments/769694705593400528/runs/c43eec7d73c94b42a6a28b35f60a79a9
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.001
Fold 0: 12.097783612252579
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/ebec2d0f0c0646438d915f0776f516fd
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: 11.47787825454347
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/43382961d5e9440a8447771ff607cb33
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: 12.651457301612362
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/9c6fae30dd6c4ec3bc8b1208b763815e
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  12.026101768646212
Average validation loss (MSE):  12.075706389469469
Average validation R2:  -16.09481758461617
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.001 at: http://localhost:5000/#/experiments/769694705593400528/runs/ffc47913ac2a47d4967d44dc7920eec3
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.0001
Fold 0: 22.726925296053363
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/bfd8b8d9e95d432eabca17e05608efbb
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: 22.044336099195423
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/d22c43a5ebb84bb4abf80a6daf64960c
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: 23.91038964956118
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/0a6a8eb039d8434893ecb9751170b6fd
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  22.888833642604805
Average validation loss (MSE):  22.893883681603324
Average validation R2:  -31.405650139495048
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-zero_LR-0.0001 at: http://localhost:5000/#/experiments/769694705593400528/runs/13d381cd24de4a8a967d142e33166ba1
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.01
Fold 0: inf
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/0ee0490c02354f3fa7ff23be7edc0bbf
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: inf
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/28c0e1ff8a034d729124a5ade6a1f972
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: inf
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/637e84f1dc7846e3b79b6f4f8973893e
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  inf
Average validation loss (MSE):  inf
Average validation R2:  -inf
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.01 at: http://localhost:5000/#/experiments/769694705593400528/runs/9153f44da4d34dcd882e6d600555ef27
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.001
Fold 0: 12.086502560700163
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/614c42153ebc44e1b6fec0246f84dbd3
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: 11.509020673087777
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/c6097004879d4e6cb8d1dbde8fe3e77c
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: 12.620819019737647
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/820d61b3352c444ba64a40158c3a2fb9
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  12.026212042807165
Average validation loss (MSE):  12.072114084508529
Average validation R2:  -16.089369574322607
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.001 at: http://localhost:5000/#/experiments/769694705593400528/runs/6b4d8a1a02bd4bbfbaa12aa83e1d386d
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.0001
Fold 0: 22.74001855718833
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/f3e650d946fb45bdb627e57e4c4fc6ef
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 1: 21.97262950960632
🏃 View run Fold-1 at: http://localhost:5000/#/experiments/769694705593400528/runs/6ec6738d1d304d1da3534972bcc06c0d
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Fold 2: 23.87412125232645
🏃 View run Fold-2 at: http://localhost:5000/#/experiments/769694705593400528/runs/23916eee2ece475ab90b649123486ba2
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
Average training loss (MSE):  22.851704640030146
Average validation loss (MSE):  22.862256439707036
Average validation R2:  -31.361509868104122
🏃 View run Reg-Normal_TrainMethod-batch_Momentum-0_WeightInit-xavier_LR-0.0001 at: http://localhost:5000/#/experiments/769694705593400528/runs/36ff9c8d99e54d198834859e6e805a0b
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528
========================================
Reg-Normal_TrainMethod-stochastic_Momentum-0_WeightInit-zero_LR-0.01
🏃 View run Fold-0 at: http://localhost:5000/#/experiments/769694705593400528/runs/74fd09a414f34f209de7c062fdf77e7d
🧪 View experiment at: http://localhost:5000/#/experiments/769694705593400528

IndexError: tuple index out of range

In [15]:
# load model from mlflow
loaded_model: Pipeline = mlflow.sklearn.load_model(
    model_uri="mlartifacts/769694705593400528/models/m-6dae5074027f480f9227c4100b49f769/artifacts/",
)

In [16]:
X_test

,brand,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
1971,Honda,2004,110000,Petrol,Individual,Manual,Third Owner,12.80,1493.0,100.00,5.0
4664,Tata,2014,291977,Diesel,Individual,Manual,First Owner,14.00,2179.0,138.10,7.0
5448,Maruti,2016,70000,Diesel,Individual,Manual,First Owner,23.20,1248.0,73.94,5.0
3333,Honda,2006,120000,Petrol,Individual,Manual,Second Owner,16.90,1497.0,100.00,5.0
2316,Maruti,2013,69000,Diesel,Individual,Manual,Second Owner,22.90,1248.0,74.00,5.0
...,...,...,...,...,...,...,...,...,...,...,...
1149,BMW,2019,8500,Diesel,Dealer,Automatic,First Owner,16.78,1995.0,190.00,5.0
5002,Maruti,2017,40000,Petrol,Individual,Manual,First Owner,20.89,1197.0,81.80,5.0
6008,Hyundai,2014,54043,Petrol,Dealer,Automatic,First Owner,18.90,1197.0,81.86,5.0
2283,Tata,2018,70000,Petrol,Individual,Manual,First Owner,17.00,1198.0,108.50,5.0
5428,Chevrolet,2013,110000,Petrol,Individual,Manual,Second Owner,18.60,1199.0,79.40,5.0

In [17]:
loaded_model.predict(X_test)

d:\AT82.03-ML-Car-Price-Prediction\.venv\Lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

array([nan, nan, nan, ..., nan, nan, nan], shape=(1607,))

In [18]:
loaded_model.steps[-1][1].__class__

utils.model.LinearRegression

In [19]:
yhat = loaded_model.predict(X_test)
mse = loaded_model.steps[-1][1].mse(y_test, yhat)
r2 = loaded_model.steps[-1][1].r_squared(y_test, yhat)

d:\AT82.03-ML-Car-Price-Prediction\.venv\Lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

In [20]:
print(mse)
print(r2)

0.0
1.0

In [21]:
loaded_model.steps[0][1].get_feature_names_out()

array(['brand_le__brand', 'fuel_le__fuel',
       'transmission_le__transmission', 'owner_le__owner',
       'seller_type_ohe__seller_type_Individual',
       'seller_type_ohe__seller_type_Trustmark Dealer',
       'num_scaler__year_imputer__year',
       'num_scaler__km_imputer__km_driven',
       'num_scaler__mileage_imputer__mileage',
       'num_scaler__engine_imputer__engine',
       'num_scaler__max_power_imputer__max_power',
       'num_scaler__seats_imputer__seats'], dtype=object)

In [22]:
loaded_model.steps[1][1].get_feature_names_out()

array(['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10',
       'x11', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3', 'x0 x4', 'x0 x5',
       'x0 x6', 'x0 x7', 'x0 x8', 'x0 x9', 'x0 x10', 'x0 x11', 'x1^2',
       'x1 x2', 'x1 x3', 'x1 x4', 'x1 x5', 'x1 x6', 'x1 x7', 'x1 x8',
       'x1 x9', 'x1 x10', 'x1 x11', 'x2^2', 'x2 x3', 'x2 x4', 'x2 x5',
       'x2 x6', 'x2 x7', 'x2 x8', 'x2 x9', 'x2 x10', 'x2 x11', 'x3^2',
       'x3 x4', 'x3 x5', 'x3 x6', 'x3 x7', 'x3 x8', 'x3 x9', 'x3 x10',
       'x3 x11', 'x4^2', 'x4 x5', 'x4 x6', 'x4 x7', 'x4 x8', 'x4 x9',
       'x4 x10', 'x4 x11', 'x5^2', 'x5 x6', 'x5 x7', 'x5 x8', 'x5 x9',
       'x5 x10', 'x5 x11', 'x6^2', 'x6 x7', 'x6 x8', 'x6 x9', 'x6 x10',
       'x6 x11', 'x7^2', 'x7 x8', 'x7 x9', 'x7 x10', 'x7 x11', 'x8^2',
       'x8 x9', 'x8 x10', 'x8 x11', 'x9^2', 'x9 x10', 'x9 x11', 'x10^2',
       'x10 x11', 'x11^2'], dtype=object)

In [23]:
kfold_scores = [
    KFoldScore(train_loss=1.0, val_loss=2.0, val_r2=0.5),
    KFoldScore(train_loss=1.5, val_loss=2.5, val_r2=0.6),
]

pd.DataFrame(kfold_scores).mean()

train_loss    1.25
val_loss      2.25
val_r2        0.55
dtype: float64

In [24]:
runs = mlflow.search_runs(search_all_experiments=True, output_format="pandas")

In [25]:
runs[runs["tags.mlflow.parentRunId"].isna()]

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.val_loss,metrics.val_r2,metrics.train_loss,metrics.avg_val_r2,...,params.batch_size,params.train_method,params.momentum,params.num_epochs,params.model_type,tags.mlflow.runName,tags.mlflow.source.name,tags.mlflow.parentRunId,tags.mlflow.user,tags.mlflow.source.type
3,767588409e1f44e8bfdd45efeea5e7dc,769694705593400528,FINISHED,mlflow-artifacts:/769694705593400528/767588409...,2025-09-10 09:03:46.714000+00:00,2025-09-10 09:04:18.008000+00:00,NaN,NaN,NaN,0.559461,...,50,mini-batch,0.9,500,Polynomial,Reg-Polynomial_TrainMethod-mini-batch_BatchSiz...,d:\AT82.03-ML-Car-Price-Prediction\.venv\Lib\s...,None,promb,LOCAL
7,6f0a06701a4540c9886625fbfc1c459f,769694705593400528,FINISHED,mlflow-artifacts:/769694705593400528/6f0a06701...,2025-09-10 08:38:33.785000+00:00,2025-09-10 08:39:46.082000+00:00,NaN,NaN,NaN,NaN,...,50,mini-batch,0.9,500,Polynomial,Reg-Polynomial_TrainMethod-mini-batch_BatchSiz...,d:\AT82.03-ML-Car-Price-Prediction\.venv\Lib\s...,None,promb,LOCAL